### no longer works with newer components
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: example-run
spec:
  serviceAccountName: build-bot
  taskRef:
    name: kaniko
  params:
    - name: IMAGE
      value: train-schedule
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/linuxacademy/cicd-pipeline-train-schedule-autodeploy.git
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: index.docker.io/ds1mk/traintest