apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  #generateName: train-sched-pr-
  name: train-sched-pr-0
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/linuxacademy/cicd-pipeline-train-schedule-autodeploy
    # - name: gitRevision
    #   value: beta-update
    # - name: pathToYamlFile
    #   value: kubernetes/picalc.yaml
    - name: imageUrl
      value: trow.kube-public.svc.cluster.local:8000/thomas/trainsched
    - name: imageTag
      value: "1.0"
    - name: pathToContext
      value: "./Dockerfile"     
  # serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi    
      #emptyDir: {} 
      # persistentVolumeClaim:
      #   claimName: trainsched-source-pvc
